### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by cholcombe973** [shepmaster/twox-hash#53]
Could you cut a new release to crates.io for the digest 0.9 support? Everything works fine when I compile against master but I'd like to not have to do that :)

**Comment by shepmaster** [comment]
Yes, that seems fine, but I'm torn on what version to pick!

For the core functionality, nothing has changed, which seems like it would indicate that I could do a semver-compatible release. However, the digest version is semver-**in**compatible, and since that's publicly exposed, it feels like I need to also perform an incompatible release...

**Comment by shepmaster** [comment]
Actually, I think I can support both versions. I'll try to whip up a branch today and I hope you'll be able to give it a quick whirl before I merge it.

**Comment by Systemcluster** [comment]
Very excited to be able to use xxh3 👍

**Comment by shepmaster** [comment]
@Systemcluster  Make sure you follow #52 then, as the xxh3 in master follows an older version of the standard.

**Comment by shepmaster** [comment]
Please give the https://github.com/shepmaster/twox-hash/tree/duel-of-digest branch a try. The main difference is that there's a `digest` feature (the same as the released 1.5 version) and a new `digest_0_9` feature, which is what you'll want to switch to.

**Comment by cholcombe973** [comment]
@shepmaster I just tested this with the `digest_0_9` feature and that fixes the compile issues. Thanks!

**Comment by shepmaster** [comment]
1.6.0 is released. hash away!
